Repository llvm4j/llvm4j, pull requests merged in 2020-10, with the labels that each got.

#184 [ci] Remove Dokka autodeploy and merge other workflows into single file
  .github/workflows/deploy.yml
  .github/workflows/execute-samples.yml
  .github/workflows/suite.yml
  Makefile
  samples/run.sh
Labels: scope:ci-cd

#185 [samples] make samples use local file only on ci machines
  samples/factorial-jit/build.gradle.kts
Labels: scope:ci-cd

#188 [ci] Updated github actions workflow to run lint job using ktlint
  .github/workflows/suite.yml
  src/main/kotlin/io/vexelabs/bitbuilder/llvm/executionengine/ExecutionEngine.kt
  src/main/kotlin/io/vexelabs/bitbuilder/llvm/executionengine/callbacks/MemoryManagerAllocateCodeSectionCallback.kt
  src/main/kotlin/io/vexelabs/bitbuilder/llvm/executionengine/callbacks/MemoryManagerAllocateDataSectionCallback.kt
  src/main/kotlin/io/vexelabs/bitbuilder/llvm/executionengine/callbacks/MemoryManagerFinalizeMemoryCallback.kt
  src/main/kotlin/io/vexelabs/bitbuilder/llvm/ir/MetadataEntries.kt
  src/main/kotlin/io/vexelabs/bitbuilder/llvm/ir/PassManager.kt
  src/main/kotlin/io/vexelabs/bitbuilder/llvm/ir/callbacks/DiagnosticHandlerCallback.kt
  src/main/kotlin/io/vexelabs/bitbuilder/llvm/target/TargetLibraryInfo.kt
  src/main/kotlin/io/vexelabs/bitbuilder/rtti/Casting.kt
  src/test/kotlin/io/vexelabs/bitbuilder/llvm/unit/executionengine/MCJITCompilerOptionsTest.kt
  src/test/kotlin/io/vexelabs/bitbuilder/llvm/unit/ir/types/FunctionTypeTest.kt
  src/test/kotlin/io/vexelabs/bitbuilder/llvm/unit/target/TargetMachineTest.kt
  src/test/kotlin/io/vexelabs/bitbuilder/llvm/unit/target/TargetTest.kt
  src/test/kotlin/io/vexelabs/bitbuilder/rtti/CastingTest.kt
Labels: scope:ci-cd

#190 Update dependencies from kotlin 1.4.0 -rc to 1.4.10
  build.gradle.kts
Labels: scope:dependencies

#193 [gradle] Set up gradle for publishing
  README.md
  build.gradle.kts
  samples/factorial-jit/build.gradle.kts
Labels: scope:ci-cd, scope:gradle

#195 [bugfix] Replace all instances of XPointer(0) with (1)
  src/main/kotlin/io/vexelabs/bitbuilder/llvm/ir/Instruction.kt
  src/main/kotlin/io/vexelabs/bitbuilder/llvm/ir/Metadata.kt
  src/main/kotlin/io/vexelabs/bitbuilder/llvm/ir/Module.kt
  src/main/kotlin/io/vexelabs/bitbuilder/llvm/ir/ModuleFlagEntries.kt
  src/main/kotlin/io/vexelabs/bitbuilder/llvm/ir/NamedMetadataNode.kt
  src/main/kotlin/io/vexelabs/bitbuilder/llvm/ir/Value.kt
  src/main/kotlin/io/vexelabs/bitbuilder/llvm/ir/attributes/AttributeString.kt
  src/main/kotlin/io/vexelabs/bitbuilder/llvm/ir/values/GlobalValue.kt
  src/main/kotlin/io/vexelabs/bitbuilder/llvm/ir/values/IntrinsicFunction.kt
  src/main/kotlin/io/vexelabs/bitbuilder/llvm/ir/values/constants/ConstantArray.kt
  src/main/kotlin/io/vexelabs/bitbuilder/llvm/ir/values/traits/DebugLocationValue.kt
Labels: scope:llvm-apis, type:bugfix
